language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports 
  - bash <(curl -s https://codecov.io/bash)